apiVersion: apps/v1
kind: Deployment
metadata:
  name: clickhouse
  creationTimestamp: null
spec:
  replicas: 1
  selector:
    matchLabels:
      service: clickhouse
  template:
    metadata:
      labels:
        service: clickhouse
    spec:
      initContainers:
      containers:
        - env:
          image: clickhouse/clickhouse-server:24.6.2
          imagePullPolicy: Always
          name: clickhouse
          ports:
            - containerPort: 8123
              protocol: TCP
            - containerPort: 9000
              protocol: TCP
          volumeMounts:
            - mountPath: "/var/lib/clickhouse"
              name: clickhouse-storage-pvc
      restartPolicy: Always
      volumes:
        - name: clickhouse-storage-pvc
          persistentVolumeClaim:
            claimName: clickhouse-storage-pvc